package com.example.demo.vo;

import java.math.BigDecimal;

public class OrderVo {


    /**
     *
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public class Order {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column order.goods_id
         *
         * @mbg.generated
         */
        private Integer goodsId;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column order.goods_name
         *
         * @mbg.generated
         */
        private String goodsName;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column order.goods_price
         *
         * @mbg.generated
         */
        private BigDecimal goodsPrice;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column order.goods_stock
         *
         * @mbg.generated
         */
        private String goodsStock;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column order.goods_id
         *
         * @return the value of order.goods_id
         *
         * @mbg.generated
         */
        public Integer getGoodsId() {
            return goodsId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column order.goods_id
         *
         * @param goodsId the value for order.goods_id
         *
         * @mbg.generated
         */
        public void setGoodsId(Integer goodsId) {
            this.goodsId = goodsId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column order.goods_name
         *
         * @return the value of order.goods_name
         *
         * @mbg.generated
         */
        public String getGoodsName() {
            return goodsName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column order.goods_name
         *
         * @param goodsName the value for order.goods_name
         *
         * @mbg.generated
         */
        public void setGoodsName(String goodsName) {
            this.goodsName = goodsName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column order.goods_price
         *
         * @return the value of order.goods_price
         *
         * @mbg.generated
         */
        public BigDecimal getGoodsPrice() {
            return goodsPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column order.goods_price
         *
         * @param goodsPrice the value for order.goods_price
         *
         * @mbg.generated
         */
        public void setGoodsPrice(BigDecimal goodsPrice) {
            this.goodsPrice = goodsPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column order.goods_stock
         *
         * @return the value of order.goods_stock
         *
         * @mbg.generated
         */
        public String getGoodsStock() {
            return goodsStock;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column order.goods_stock
         *
         * @param goodsStock the value for order.goods_stock
         *
         * @mbg.generated
         */
        public void setGoodsStock(String goodsStock) {
            this.goodsStock = goodsStock;
        }
    }
}
