package com.example.demo.vo;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
public class UserVo {


    /**
     *
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fanuser
     *
     * @mbg.generated do_not_delete_during_merge
     */
    @ApiModelProperty(value = "用户id")
        private Integer id;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column fanuser.name
         *
         * @mbg.generated
         */
        @ApiModelProperty(value = "用户名")
        private String name;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column fanuser.password
         *
         * @mbg.generated
         */
        @ApiModelProperty(value = "用户密码")
        private String password;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column fanuser.create_time
         *
         * @mbg.generated
         */
        @ApiModelProperty(value = "创建时间")
        private Date createTime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column fanuser.update_time
         *
         * @mbg.generated
         */
        @ApiModelProperty(value = "更新时间")
        private Date updateTime;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column fanuser.id
         *
         * @return the value of fanuser.id
         *
         * @mbg.generated
         */
        public Integer getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column fanuser.id
         *
         * @param id the value for fanuser.id
         *
         * @mbg.generated
         */
        public void setId(Integer id) {
            this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column fanuser.name
         *
         * @return the value of fanuser.name
         *
         * @mbg.generated
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column fanuser.name
         *
         * @param name the value for fanuser.name
         *
         * @mbg.generated
         */
        public void setName(String name) {
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column fanuser.password
         *
         * @return the value of fanuser.password
         *
         * @mbg.generated
         */
        public String getPassword() {
            return password;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column fanuser.password
         *
         * @param password the value for fanuser.password
         *
         * @mbg.generated
         */
        public void setPassword(String password) {
            this.password = password;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column fanuser.create_time
         *
         * @return the value of fanuser.create_time
         *
         * @mbg.generated
         */
        public Date getCreateTime() {
            return createTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column fanuser.create_time
         *
         * @param createTime the value for fanuser.create_time
         *
         * @mbg.generated
         */
        public void setCreateTime(Date createTime) {
            this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column fanuser.update_time
         *
         * @return the value of fanuser.update_time
         *
         * @mbg.generated
         */
        public Date getUpdateTime() {
            return updateTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column fanuser.update_time
         *
         * @param updateTime the value for fanuser.update_time
         *
         * @mbg.generated
         */
        public void setUpdateTime(Date updateTime) {
            this.updateTime = updateTime;
        }
    }

